### ISSUE TITLE
`prepare_checkpoint1()` could include remaining 'Data processing related' config parameters

### ISSUE THREAD

**Issue by dtm2451** [UCSF-DSCOLAB/CyTOF_pipeline#6]
In the config file there are params...
```
#### Data processing related
arcsinh_cofactor: 5
subsample: FALSE
subsample_n: 4000
exclude_controls: FALSE
```

...but only the arcsinh transformation is part of the `prepare_checkpoint1()` functionality.

Potentially, could add subsampling and control exclusion.

For my use case, I am ignoring controls that were only included for batch correction purposes.  I had to remove them manually from my trans_exp before running the function.

Not a huge deal, but might be nice?

Additionally, if the `prepare_checkpoint1()` function actually handled everything / most of what checkpoint1 does accomplish, we could maintain just `prepare_checkpoint1()` and plug that in to cytof_pipeline.R in place of the relevant code.

Seems like it should be fairly simple to do.  I could take this work on myself if you'd like.  Just let me know!

**Comment by ravipatel4** [comment]
That sounds like a great idea, Dan! Please feel free to do those modifications. 
Thanks.
